### ISSUE TITLE
Automate lab publication updates

### ISSUE THREAD

**Issue by nniiicc** [BillHoweLab/billhowelab.github.io#1]
Motivation: 
- Lab websites are tedious to maintain 
- We can script our way out of this problem

Broadly, the steps might include querying different sites on the web for bibligoraphic data and then regularly pushing updates to the lab website.

With a little more detail

Query
- Arxiv, Crossref, SocArxiv by author + affiliation, or ORCID
- push JSON response to an authors folder in lab website repo 

Cron Job
- Run nightly and update the author folder with any new  publication found

GH Action 
- When a new publication is added, recompile publications page and push new build of website

Stretch goals 

If designed correctly you could also automated updates to a... 
- - Personal website
- - CV (converting the JSON object to a bibtex entry)
- - Other lab or affiliated research group's websites... 

While we're dreaming ... 
- Share scripts w/ other research groups in DataLab (or what will be known as DSCO 🪩) 
- Set up a weekly email digest with all new publications or preprints published by different groups / members of the DataLab
- Profit (e.g. find people working on similar topics)

**Comment by billhowe** [comment]
I'm still keen on manually maintaining papers on lab site, but with some way of referencing a paper in multiple places on this site without copying.  Some reasons:

- Curation is needed anyway:
  - Bibliographic scrapes include false positives and false negatives
  - Lab members need control over what they advertise here -- for example, anything that I wasn't involved in probably shouldn't be here.  Might be hard to query for this; seems to warrant case-by-case decisions.
- We want auxiliary information, not just references 
  - Teaser images are useful on web to associate with a paper, but won't come from bibliographic scrapes.  So there will be some manual curation regardless.
  - We will probably want to serve our own pdfs rather than linking to paywalls.  We're allowed to under almost all publishing agreements to at least post the manuscript version, and it makes it far far easier for people to access. Plus, I don't have much sympathy for publishers.   
- We need to maintain content anyway, even if we automate papers.  We can't automate news posts and project info.

**Comment by light-and-salt** [comment]
So let's close this issue for now? Can re-open in the future if we change our mind :)
